### ISSUE TITLE
HackRF mode missing from screen, cannot update firmware

### ISSUE THREAD

**Issue by FT847** [sharebrained/portapack-hackrf#106]
I must have installed an older version of the Portapack firmware. Now, I cannot update the firmware since the HackRF menu item no longer exists. 
I cannot even reset using dfu_hack_one application. 
My OS is Windows 10 home. 

![img_20161202_142731643](https://cloud.githubusercontent.com/assets/24322284/20849424/3c5746ca-b89c-11e6-9332-e57fb2124326.jpg)
![portapack issue1](https://cloud.githubusercontent.com/assets/24322284/20849443/560efb80-b89c-11e6-85c2-385f84055151.jpg)
![portapack issue1a](https://cloud.githubusercontent.com/assets/24322284/20849444/56162630-b89c-11e6-89ca-0c801d0be3a4.jpg)

Thank you in advance for your assistance.

**Comment by jboone** [comment]
@FT847 I've contacted you via e-mail, but let me also write the answer publicly so it can help other Windows users -- and serve as a reminder to me to update the Wiki with this process.

Uninstall existing copies of the PortaPack firmware tool, to ensure a clean slate.

Find the latest PortaPack firmware under the "Releases" section of this repository.

Download and install "PortaPack.Firmware.Tool" executable.

Inside the PortaPack program group, you should find a program (actually a batch file) called "HackRF Mode via DFU". Run that program and follow the instructions.

Once you press a key, the HackRF firmware will be loaded into the memory of the HackRF. It will not persist, so do not unplug or reset the HackRF.

Now, try to use either of the "Flash PortaPack Firmware" or "Flash HackRF One Firmware" tools. Once you've gone through that process, you should be good to go with whichever firmware you chose to install.

**Comment by FT847** [comment]
Jason. I loaded 20160728 and got the result as shown in the "DFU-Flash.jpg". Any ideas? -----Original Message-----

**Comment by FT847** [comment]
Issue resolved, thanks again for your quick response.
