### ISSUE TITLE
HackRF One FW update

### ISSUE THREAD

**Issue by KC5CQW** [sharebrained/portapack-hackrf#108]
Include the latest FW release: 2017.02.1 to replace the 2015 version.

**Comment by jboone** [comment]
Firmware is incorporated on this testing branch: https://github.com/sharebrained/portapack-hackrf/tree/working_20160728.1

Please let me know how it works for you. Cursory tests worked fine for me.

**Comment by jboone** [comment]
Also addressed in commit 66d66b57ab8ef89e00a3491532af8c620f20a9e8 on master.

**Comment by jboone** [comment]
Re-opening for futher testing and feedback. Builds for testing are available here:

https://portapack-h1-builds.s3.amazonaws.com/sharebrained/portapack-hackrf/140/140.1/build/firmware/portapack-h1-firmware-66d66b5.zip

https://portapack-h1-builds.s3.amazonaws.com/sharebrained/portapack-hackrf/140/140.1/build/firmware/portapack-h1-firmware-66d66b5.tar.bz2

**Comment by jboone** [comment]
2017.02.1 is distributed in the newest PortaPack firmware releases and is working, apparently without issue.
