### ISSUE TITLE
Integration Build Link Error

### ISSUE THREAD

**Issue by KC5CQW** [sharebrained/portapack-hackrf#109]
Unable to download, see the following error:

<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>Giorgiofox/portapack-hackrf/3/3.1/build/firmware/portapack-h1-firmware-ca7bb09.tar.bz2</Key>
<RequestId>4085F0BD4563173C</RequestId>
<HostId>PrvOf6+Oqjl25zn2QqNE3sjIGzQZSbsND10VwC3bb3wpbInUIr65gTzeQdAzCxYKVy3hiZjiGmg=</HostId>
</Error>

**Comment by jboone** [comment]
The build you site is for Giorgio's fork. Builds for GitHub accounts other than "sharebrained" do not have rights to the bucket on Amazon S3 where I put my builds. If other forks want to provide continuous integration, they'll need to set up their own S3 buckets or another solution for build artifacts.
