### ISSUE TITLE
Provide indication that no PortaPack detected before HackRF mode

### ISSUE THREAD

**Issue by jboone** [sharebrained/portapack-hackrf#118]
For diagnostic purposes, it'd be good to tell if a PortaPack was detected before the firmware reverts to HackRF mode. That way, we can tell if it's the HackRF code that's running directly, or if there's PortaPack firmware, not detecting a PortaPack (which might be present!), and then running HackRF mode.

**Comment by KC5CQW** [comment]
I think I have a problem that sounds like this issue. Somehow, I hosed the PP firmware and my computer says no HRF found when I try to reload the PP release FW. I reinstalled the HRF DFU file from the release package and it loaded fine. I went back to both the PP and HRF FW batch utilities and they still show 0 PP and 0 HRF. The only option next is to "hit any key" and the utility closes out., Currently, the only FW running or installed is the DFU loaded HRF from the windows FW installer package. This is starting to sound like "Brick in the Wall" - Pink Floyd. No pudding, no meat. Please don't let me throw this brick into a wall!

**Comment by jboone** [comment]
This issue is a feature request. Your issue is something else. I'll contact you by email to work through this.

**Comment by KC5CQW** [comment]
Ok thanks, I’ll delete. 


73, Damon

**Comment by jboone** [comment]
Latest HackRF firmware makes use of PortaPack if present. So this is moot.
