### ISSUE TITLE
Baseband processor sampling rate 

### ISSUE THREAD

**Issue by salvitti** [sharebrained/portapack-hackrf#122]
Hi,

I have noted the sampling rate of baseband processor was set at 3072000.
Why this strange value?
Is it possible to increase the sampling rate up to 20 MHz?

**Comment by jboone** [comment]
Can you say which file you're looking at? Most likely that is an audio mode. In which case, the sampling rate is chosen to be an even multiple of the audio output frequency, to simplify the math of the sample decimation process. There are other modes (for instance the wideband spectrum analysis mode) that use a 20MHz sampling rate. In that case, there is very little CPU power left to do anything but the spectrum analysis. The processor on the HackRF is only 204 MHz and has no fancy peripherals like a GPU.
