### ISSUE TITLE
Possible to make Portapack recieve drone camera video?

### ISSUE THREAD

**Issue by Zeeko22** [sharebrained/portapack-hackrf#133]
I wonder if it possible to get portapack able to recieve dronecamera transmitting videos, i think it would match and be very intresting .. Have anyone suggetion if i can download any software that can make this possible?

**Comment by jboone** [comment]
Hi @Zeeko22. It depends on the drone. Do you have any information on the transmitter used on the drone?

I have seen drones that use 5.8 GHz transmitters to send NTSC-type signals that are frequency modulated. It might be possible to decode that -- maybe not at the full frame rate, or full resolution, or in color. A lot of code would need to be written to accomplish that, but I believe it would be possible.
