### ISSUE TITLE
I update the firmware, ,but the screen is always blank.

### ISSUE THREAD

**Issue by freeworld1981** [sharebrained/portapack-hackrf#134]
I updated the firmware and CPLD, all successfully ,but the screen is always blank, dark no light. 

the led only green/yellow/red light.

where is the problem?

**Comment by jboone** [comment]
@freeworld1981 It's hard to say. Which LEDs are lit? Just the 3V3, 1V8, and RF power LEDs? Or are the USB (green), RX (yellow), or TX (red) LEDs also lit?

Which version of PortaPack firmware are you using? Is it a released version, or are you compiling it yourself?

Which PortaPack hardware revision are you using? There's a date code on the front of the PortaPack, near the LCD panel.

**Comment by pipi111** [comment]
same here i have githus 5ec8164e
latest portapack hardare version
latest firmware
downloaded from original source

**Comment by kevtheskin** [comment]
Hello Jared, Im have the same problem. I tried the havoc software and i think my unit is a brick now?. Cheers Kev

**Comment by jboone** [comment]
@kevtheskin, @pipi111, @freeworld1981: Please try the latest released PortaPack firmware and report your results: https://github.com/sharebrained/portapack-hackrf/releases/tag/20190405

**Comment by jboone** [comment]
Are your problems resolved by using the release firmware?

**Comment by jboone** [comment]
No action on this thread. Closing.

**Comment by Mars0117** [comment]
Hi.
I faced that problem. Original firmware not working https://github.com/sharebrained/portapack-hackrf/releases/tag/20190405.
Before the problem the original firmware and havoc worked.

**Comment by millercontracting2017** [comment]
Same problem here also any fix yet?
