### ISSUE TITLE
try to reflash the cpld 5M40ZE64 by JTAG, but get wrong pof.

### ISSUE THREAD

**Issue by freeworld1981** [sharebrained/portapack-hackrf#135]
hi,  I try to reflash the the cpld 5M40ZE64,  but when I use quartus to compail the code, get one pof.
but it has a problem,  I check the code, the right should be like that.
!NOTE "USERCODE" "0018B4E3";
!
!NOTE "CHECKSUM" "0018B85B";

but what I got ：
 "USERCODE" "0018A518";
 "CHECKSUM" "0018A968";

and the size of  SVF file is different to,  it is 266K, not 254K.

where is the problem?

**Comment by jboone** [comment]
@freeworld1981 There's no guarantee that the bitstream is the same between successive builds of the exact same source code. Does your build of the bitstream work correctly?

**Comment by jboone** [comment]
Nothing heard. Closing.
