### ISSUE TITLE
c16 files format

### ISSUE THREAD

**Issue by VeloVolo** [sharebrained/portapack-hackrf#139]
Could not figure how to import recorded c16 files into gnuradio. Trying to set "source file" and "throttle" blocks, but do not see proper waterfall chart. What data contain these files? complex, float..?
Could not find any information about these files.

**Comment by jboone** [comment]
Sorry for the delay.

These are 16-bit signed integers. Two 16-bit signed integers make up one complex (IQ) pair -- one complex sample. I would recommend using the "IShort to Complex" block to do this. You may also need to multiply by a constant (e.g. 1.0 / 32768.0) to normalize the complex float samples to +/- 1.0.

I hope that helps.
