### ISSUE TITLE
reflash firmware using windoes?

### ISSUE THREAD

**Issue by kiwiandy** [sharebrained/portapack-hackrf#145]
I have uploaded hackrf_one_usb.dfu to my device using DF-UTIL command line on my Windows PC.

How do I get get the Portapack code flashed into the SPI flash?

**Comment by Macintoshsh** [comment]
https://github.com/sharebrained/portapack-hackrf/wiki/Updating%20Firmware%20Windows


Sent from  iPhone A_Macintosh
nr +79268246716

**Comment by kiwiandy** [comment]
> https://github.com/sharebrained/portapack-hackrf/wiki/Updating%20Firmware%20Windows Sent from iPhone A_Macintosh nr +79268246716
> […](#)
> 29 нояб. 2019 г., в 01:28, kiwiandy ***@***.***> написал(а): ﻿ I have uploaded hackrf_one_usb.dfu to my device using DF-UTIL command line on my Windows PC. How do I get get the Portapack code flashed into the SPI flash? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks but as my screen is blank on the Portapack, I cannot set the portapack to HACKRF mode so that I can use that tool!

**Comment by Macintoshsh** [comment]
So it’s tool don’t using screen portapack. It’s flashing from computer. 
I’m flash from Ubuntu and dfu utils. 
I’m connect and flashing HACKRf  and  portapack. 
After flashing all start. 

Sent from  iPhone A_Macintosh
nr +79268246716

> 29 нояб. 2019 г., в 21:16, kiwiandy <notifications@github.com> написал(а):
> 
> Thanks but as my screen is blank on the Portapack, I cannot set the portapack to HACKRF mode so that I can use that tool

**Comment by jboone** [comment]
Good answer. A demo of how to do Windows flashing is here: https://www.youtube.com/watch?v=5G5blPPIIBo

Since there was no reply, I'm going to call this one closed.
