### ISSUE TITLE
Compatibility with the Portapack H2

### ISSUE THREAD

**Issue by RChadwick7** [sharebrained/portapack-hackrf#147]
While I'm not exactly sure where it came from, the usual China sources are selling a H2, which has a much bigger screen. The controls are different, but look like they have compatible functions. I'm assuming/hoping the larger screen has the same resolution. Does anyone know if there are any electrical differences between the original Portapack and the H2? Will the Portapack firmware work on the H2 unmodified?

**Comment by MakarenkoSV** [comment]
Hey. Yes it works.
