### ISSUE TITLE
SDCard maximum supported size

### ISSUE THREAD

**Issue by mrspirytus** [sharebrained/portapack-hackrf#152]
I was wondering after googling around what is the largest supported SD card portapack can recognize? What is preferred? File system format? Any specific brands work better then others?

Cheers

**Comment by jboone** [comment]
Hi. A little bit of this information is in the Wiki. I will add more detail in a moment.

https://github.com/sharebrained/portapack-hackrf/wiki/General-Use#microsd-card-socket
