### ISSUE TITLE
Provide waterfall in receiver WFM mode

### ISSUE THREAD

**Issue by jboone** [sharebrained/portapack-hackrf#16]
Code needs to be restructured to do fewer FFTs due to less available CPU cycles. So time-domain coverage will be poorer than in other modes. But it'd still be useful to have...

**Comment by aernan** [comment]
I would use this feature. Even if you could not see as much of the spectrum.

**Comment by KC5CQW** [comment]
Useful for visualizing modulation drive and deviation. It need not have a high resolution as most WFM signals are audio only. The display refresh can be in the order of seconds or long enough for an average spoken sentience to be graphically populated on the screen. (5-10 sec.)

**Comment by aernan** [comment]
Many WFM signals have a HD Radio signal on them as well. Would be nice to see the waveform to see if HD is there. http://hdradio.com/ https://www.ibiquity.com/technology

**Comment by KC5CQW** [comment]
Agreed! This is a basic feature found in GQRX.

**Comment by jboone** [comment]
Quick implementation in "wfm_waterfall" branch, but scrolls too quickly and hangs sometimes. A debugger will be necessary, and I don't have one on-hand at the moment.

**Comment by jboone** [comment]
Initial filtering and decimation steps may need to be tweaked. CIC filter characteristics seem to be visible in the waterfall, which reduces its utility.

**Comment by jboone** [comment]
Duplicate of #63, which is now closed.
