### ISSUE TITLE
Is portapack-jam-mode able to jam Bluetooth and WiFi? 

### ISSUE THREAD

**Issue by All3xJ** [sharebrained/portapack-hackrf#163]
Since hackrf can cover 20mhz of bandwidth, and Bluetooth and WiFi are wider, I was wondering if portapack can jam them with TX sweep

**Comment by eried** [comment]
Probably yes, because you can select multiple ranges but I have not tried personally.

**Comment by Commander-Crash** [comment]
No unless you have a serious amp attached to the hackrf.

**Comment by All3xJ** [comment]
> No unless you have a serious amp attached to the hackrf.

yes I have. but how to do that?
