### ISSUE TITLE
Improve firmware update experience

### ISSUE THREAD

**Issue by jboone** [sharebrained/portapack-hackrf#2]
Especially for Windows, but other platforms could use more love, too.

**Comment by KC5CQW** [comment]
Not much luck here compiling from src on OS X...

**Comment by jboone** [comment]
Can you provide details? I am developing on OS X 10.10.5, so it *should* work just fine.

**Comment by KC5CQW** [comment]
I couldn't get the ARM compiler to instal on my X.9 system.

**Comment by jboone** [comment]
OK, moving this to new issue #60. Please follow up with more details there.

**Comment by jboone** [comment]
HackRF Mode in the new firmware will help a bit with this, eliminating the need for DFU mode except in dire circumstances where the firmware on the device is non-functional.

**Comment by jboone** [comment]
[Windows firmware tool](https://github.com/sharebrained/portapack-hackrf/wiki/Updating%20Firmware%20Windows) is now available.
