### ISSUE TITLE
Adapt bootstrap/Makefile to work with dfu-util 0.8.

### ISSUE THREAD

**Issue by jboone** [sharebrained/portapack-hackrf#24]

**Comment by jboone** [comment]
"make program" target is now in firmware/Makefile, arguably where it belongs.

**Comment by aernan** [comment]
the workaround is:
dfu-util --device 1fc9:000c --download hackrf_one_usb_ram.dfu --reset
hackrf_spiflash -w portapack-h1-firmware.bin

**Comment by ZeroChaos-** [comment]
https://github.com/sharebrained/portapack-hackrf/blob/master/firmware/Makefile#L55

isn't that what it already does? I don't understand how this is a "workaround"

**Comment by jboone** [comment]
At some point, I made this work, or it fixed itself. I've been using dfu-util 0.8 for quite a while now. It complains about not having a valid DFU suffix, or the CRC not matching, which seems like a different issue. Closing this.
