### ISSUE TITLE
Means to adjust receiver channel bandwidth

### ISSUE THREAD

**Issue by jboone** [sharebrained/portapack-hackrf#33]
Should be easy enough to re-assign the FIR taps.
Adjust spectrum samples decimation factor to make sure aliasing is minimized.

**Comment by aernan** [comment]
I could see this being like a zoom in out on the screen feature.

**Comment by aernan** [comment]
You can adjust the squelch and receive bandwidth in this app.
android app RF Analyzer https://play.google.com/store/apps/details?id=com.mantz_it.rfanalyzer
probably do something similar.

**Comment by jboone** [comment]
Plumbing is there as of commit 28be223ace91d6bac55dc468789ffa0de57904c4. (It took until this commit to get something that was compilable, due to a merge-oops.)

**Comment by jboone** [comment]
NBFM channel filter can be varied between 8.5kHz, 11kHz, and 16kHz widths, with attendant adjustments to deviation (2.5 or 5k), as of commit ceef8d32d3b5da9a4faf7b98cad7ae677c63a600.

**Comment by KC5CQW** [comment]
Please explain the deviation adjustments. Is this automatic or user variable?

**Comment by jboone** [comment]
Closing this and continuing work on channel bandwidth adjustment for CW/AM/SSB via issue #86.
