### ISSUE TITLE
Add touch screen calibration

### ISSUE THREAD

**Issue by jboone** [sharebrained/portapack-hackrf#4]
During manufacturing, touch screens seem pretty consistent (don't need calibration), but PortaPacks might "feel" better to use if the touch screen was precisely calibrated.

**Comment by KC5CQW** [comment]
This would be needed if stylus or gesture support is implemented some day. Perhaps some type of scalable waterfall zoom.

**Comment by jboone** [comment]
Implemented in commit 24fa97439d7ca9524f892e5b41996d3a39695649.

**Comment by Jean-france** [comment]
Hi,
I have HAVOC firmware  on my HK. The touch screen doesn't work. Impossible to calibrate it, nothing do even i touch the screen.
Do you have a idea ?
Many thanks in advance.
Best regards,
Jean
