### ISSUE TITLE
Screen shot feature

### ISSUE THREAD

**Issue by jboone** [sharebrained/portapack-hackrf#41]
Save to SD card, don't bother with compression. Maybe the simplest of PNG formats.

**Comment by aernan** [comment]
I would use that feature. As long as it's easy enough to activate (buttons).

**Comment by jboone** [comment]
Whoops, forgot to close this. Implemented in [20160222 release](https://github.com/sharebrained/portapack-hackrf/releases/tag/20160222). Next release, due Real Soon Now(tm), saves to incrementing filenames.
