### ISSUE TITLE
HackRF firmware image padding with dd yields zero-byte file.

### ISSUE THREAD

**Issue by jboone** [sharebrained/portapack-hackrf#42]

**Comment by jboone** [comment]
Reports from issue #55, from a Ubuntu 15.04 user, are that this fix isn't working. Reopening...

**Comment by splaspood** [comment]
head -c 0x10000 /dev/zero| cat hackrf_one_usb_ram.dfu - | head -c 0x10000 > hackrf_one_usb_ram_dfu_pad.bin
head: 0x10000: invalid number of bytes
head: 0x10000: invalid number of bytes

**Comment by splaspood** [comment]
Ok, I think I see the problem.   I had a 0 byte file lying around from before, and make clean doesn't remove it, so when I rebuilt it did not re-create the pad file using the new head method.    Rebuilding now to confirm.

**Comment by splaspood** [comment]
Confirmed.

**Comment by jboone** [comment]
I should rewrite the image-building process as a Python script. It will be more predictable. And as a side benefit, it should work in Windows, unlike my current cat and head and /dev/zero approach, or even the older dd approach.

**Comment by jboone** [comment]
Rewritten and committed. I'm closing this again. Hopefully I won't have to open it a third time. :-)
