### ISSUE TITLE
Additional Demodulation Modes

### ISSUE THREAD

**Issue by KC5CQW** [sharebrained/portapack-hackrf#48]
Implement Dubble side-band, Upper and Lower side-band, Contentious Wave modes for use in spectrum analysis and communications monitoring. 
Provide variable pass-band tuning width and carrier offset features to accompany all demodulation types. (This may be a separate "issue" request, sorry!)

**Comment by KC5CQW** [comment]
Yes, similar to #33.

**Comment by KC5CQW** [comment]
If possible, I/Q output on the audio line for demodulation by a secondary "computer" would be great as well. This can be a simple settings check box. Demodulated audio vs. raw I/Q.

**Comment by jboone** [comment]
AM (DSB) and SSB (USB/LSB) are supported as of commit ceef8d32d3b5da9a4faf7b98cad7ae677c63a600.

**Comment by KC5CQW** [comment]
Yes!, this makes me happy!
Now for a future feature option request... Auto display zoom when changing BW. Oh yea, and TX of course. 

73, Damon
