### ISSUE TITLE
Flashing error

### ISSUE THREAD

**Issue by holiman** [sharebrained/portapack-hackrf#53]
I get this error when trying to flash the portapack firmware: 

	#sudo dfu-util --device 1fc9:000c --download hackrf_one_usb_ram.dfu --reset
	dfu-util 0.5

	(C) 2005-2008 by Weston Schmidt, Harald Welte and OpenMoko Inc.
	(C) 2010-2011 Tormod Volden (DfuSe support)
	This program is Free Software and has ABSOLUTELY NO WARRANTY
	
	dfu-util does currently only support DFU version 1.0
	
	Filter on vendor = 0x1fc9 product = 0x000c
	Opening DFU USB device... ID 1fc9:000c
	Run-time device DFU version 0100
	Claiming USB DFU Runtime Interface...
	Determining device status: state = dfuIDLE, status = 0
	WARNING: Runtime device already in DFU state ?!?
	Found Runtime: [1fc9:000c] devnum=0, cfg=1, intf=0, alt=0, name="DFU"
	Claiming USB DFU Interface...
	Setting Alternate Setting #0 ...
	Determining device status: state = dfuIDLE, status = 0
	dfuIDLE, continuing
	DFU mode device DFU version 0100
	Device returned transfer size 2048
	DFU CRC does not match
	Unsupported DFU file revision 0000

**Comment by jboone** [comment]
dfu-utils must be version 0.7 or 0.8. I recommend 0.7, as it is the most extensively tested with HackRF.

I will update the documentation to be more specific.
