### ISSUE TITLE
Wideband spectrum analysis

### ISSUE THREAD

**Issue by jboone** [sharebrained/portapack-hackrf#6]
Add mode to sweep the radio across a frequency range, capture baseband, either FFT or calculate average/peak power, and record/display.

**Comment by aernan** [comment]
Would be excellent to use device like a scanner. Search across a very wide band to find signals. Would be fine if single pass simple drew a DB to frequency graph.

**Comment by jboone** [comment]
Addressed as of commit 3fea68d777c553b9523cbae41d89160ce428c676. For now, a separate receiver mode. Will refine as time goes on.
