### ISSUE TITLE
PPM Menu location

### ISSUE THREAD

**Issue by KC5CQW** [sharebrained/portapack-hackrf#64]
Once the settings menu is implemented, migrate the PPM correction factor setting(s) over to regain screen real estate for other uses.

**Comment by jboone** [comment]
There is now a PPM setting in the Setup menu. But I will also keep the PPM setting in the receiver frequency options "panel", as I find it very convenient to make small adjustments. Perhaps there's a better feature waiting to get out, though -- a "fine" control that doesn't require switching steps (which I find somewhat arduous).

I did condense the text next to the PPM field, from "Corr. ### PPM" to "### PPM". So a little real estate is reclaimed.
