### ISSUE TITLE
Changing ppm offset in main menu doesn't take effect until changed on waterfall

### ISSUE THREAD

**Issue by r4v5** [sharebrained/portapack-hackrf#67]
Steps to reproduce:
* Power on the Portapack
* Wheel down to Setup -> Frequency Correction
* Change this value
* Back out to the main menu, start Receiver
* Observe that the waterfall hasn't changed to reflect the offset, but if you highlight the frequency it lists the new PPM value
* Select PPM value, rock left or right
* PPM now immediately jumps into effect

This happens on a portapack running aa733b1. The offset does get stored and persists across power-on/power-off, though, which is nice.

**Comment by jboone** [comment]
Hmmm, I think I was able to reproduce this. Notes to myself for when I tackle this: PPM seems synchronized between receiver view and setup view. But actual tuned frequency is not altered after changing PPM in setup view -- returning to receiver view, signal still appears at offset seen before the PPM adjustment.

**Comment by jboone** [comment]
I believe this is addressed in commit a9451c17b4ee18ddb7755b9111990a0b25ddeda9.
