### ISSUE TITLE
Bandwidth adjustment remains after adjusting from NFM to WFM or SPEC.

### ISSUE THREAD

**Issue by rjmendez** [sharebrained/portapack-hackrf#75]
Minor UI glitch noticed after flashing 937dad6, the bandwidth adjustment will remain visible when scrolling through modes. Possibly added in 3f86a7c?

**Comment by jboone** [comment]
Thanks. I think it's a repaint problem. The bandwidth options view can't be navigated to (receive focus), so it suggests it's not really there. I'll check the code and see what I've missed.

**Comment by jboone** [comment]
Ugh. This is due to a terrible weakness and lack of proper design effort of the widget painting scheme. I don't think I'll have time to fix it (properly) before the next release. There might be a dirty, filthy, disgusting work-around I could manage...

**Comment by jboone** [comment]
This issue is addressed in some indeterminate commit in the last month or so. It will appear in the next release, and appears now in Travis-CI builds.
